# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: 5

development:
  <<: *default
  database: horsetime_development
  username: horsetime
  password: horsetime

test:
  <<: *default
  database: horsetime_test
  username: horsetime
  password: horsetime

production:
  <<: *default
  database: horsetime_production
