export const LOAD_USERS = 'LOAD_USERS';
export const LOAD_USERS_FULFILLED = 'LOAD_USERS_FULFILLED';

export const SEARCH_USERS = 'SEARCH_USERS';
export const SEARCH_USERS_FULFILLED = 'SEARCH_USERS_FULFILLED';
export const SEARCH_USERS_REJECTED = 'SEARCH_USERS_REJECTED';
export const CLEAR_SEARCH = 'CLEAR_SEARCH';

export const SELECT_SKATER = 'SELECT_SKATER';
